name: pyleo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cartopy>=0.21.0
  - xarray=2023.4.1
  - Bottleneck=1.3.4
  - dask=2023.4.0
  - climlab
  - pip
  - jupyter=1.0.0
  - jupyterlab=3.5.2
  - pip:
    - pangaeapy
    - pyleoclim==0.11.0
    - watermark
